### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bwreid** [DrekStyler/simple-site#1]
🐢 
- Your HTML is sooooo close to being valid!
- Your images don't work currently because the path has them being in an `images/` folder.
- If you remove the first image (or remove the `width` property) everything floats upwards. Review the `clear: both;` property to fix this!
- [index.html, L8-22](https://github.com/DrekStyler/simple-site/blob/master/turtle.html#L8-L22): Your `header` should be inside of the `body` tag.
- [index.html, L25-37](https://github.com/DrekStyler/simple-site/blob/master/turtle.html#L25-L37): Beware of your indentation!
- If you choose to copy a normalizer/reset into your stylesheet, try and find the minified version!
- [main.css, L452](https://github.com/DrekStyler/simple-site/blob/master/main.css#L452): I would stay away from selecting based on ID -- instead, use classes.
- [main.css, L483](https://github.com/DrekStyler/simple-site/blob/master/main.css#L483): I would aways include the 0 (e.g. `0.75`).
- [main.css, L523](https://github.com/DrekStyler/simple-site/blob/master/main.css#L523): This little guy seems to just be hanging out.

Nice job using flexbox! Work through your file structure to make sure everything shows up and consider adding comments to your CSS to distinguish between sections. Finally, definitely take a look at `float` and `clear` once more.

Make the above changes and push back to Github. Let me know if you have any questions!

**Comment by DrekStyler** [comment]
Hey Wes. I made the changes above. I have some questions about linking multiple stylesheets and best practices. Hope you had a great weekend!
